# Crawling web detik.com

In [1]:
import sys

print(sys.executable)

C:\Users\javier\Downloads\PPW\enWebmining\Scripts\python.exe

In [2]:
import trafilatura

print("Trafilatura berhasil digunakan")

Trafilatura berhasil digunakan

In [4]:
pip install requests beautifulsoup4 pandas lxml

Requirement already satisfied: requests in .\enWebmining\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in .\enWebmining\Lib\site-packages (4.15.0)
Requirement already satisfied: pandas in .\enWebmining\Lib\site-packages (3.0.5)
Requirement already satisfied: lxml in .\enWebmining\Lib\site-packages (6.1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in .\enWebmining\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in .\enWebmining\Lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in .\enWebmining\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\enWebmining\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in .\enWebmining\Lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in .\enWebmining\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=2.3.3 in .\enWebmining\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\enWebmining\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\enWebmining\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\enWebmining\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import requests
import pandas as pd
import trafilatura
import time
import os

from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse

In [18]:
session = requests.Session()

session.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/131.0 Safari/537.36"
    ),
    "Accept-Language": "id-ID,id;q=0.9,en;q=0.8"
})

print("Session siap")

Session siap

### Fungsi mengambil halaman

In [19]:
def get_html(url):
    try:
        response = session.get(
            url,
            timeout=20
        )

        response.raise_for_status()

        return response.text

    except requests.RequestException as e:
        print(f"Gagal mengambil halaman: {url}")
        print(f"Error: {e}")
        return None

### Tes koneksi ke detik sport

In [20]:
sport_home = "https://sport.detik.com/"

html = get_html(sport_home)

if html:
    print("Berhasil mengambil halaman Sport")
    print("Panjang HTML:", len(html))
else:
    print("Gagal mengambil halaman Sport")

Berhasil mengambil halaman Sport
Panjang HTML: 268626

### Tes koneksi finance

In [21]:
finance_home = "https://finance.detik.com/"

html_finance = get_html(finance_home)

if html_finance:
    print("Berhasil mengambil halaman Finance")
    print("Panjang HTML:", len(html_finance))
else:
    print("Gagal mengambil halaman Finance")

Berhasil mengambil halaman Finance
Panjang HTML: 340271

### Fungsi mengambil URL artikel

In [22]:
def get_article_links(page_url, domain):
    html = get_html(page_url)

    if not html:
        return []

    soup = BeautifulSoup(html, "lxml")

    article_links = set()

    for a in soup.find_all("a", href=True):

        href = a["href"].strip()

        # Mengubah URL relatif menjadi URL lengkap
        full_url = urljoin(page_url, href)

        parsed = urlparse(full_url)

        # Hanya mengambil domain yang sesuai
        if parsed.netloc != domain:
            continue

        # Hilangkan fragment
        full_url = full_url.split("#")[0]

        # Hanya HTTP/HTTPS
        if parsed.scheme not in ["http", "https"]:
            continue

        article_links.add(full_url)

    return list(article_links)

### Tes mengambil URL Sport

In [23]:
sport_urls_test = get_article_links(
    "https://sport.detik.com/",
    "sport.detik.com"
)

print("Jumlah URL ditemukan:", len(sport_urls_test))

for url in sport_urls_test[:10]:
    print(url)

Jumlah URL ditemukan: 73
https://sport.detik.com/sepakbola/uefa/d-8655331/luis-enrique-nggak-mau-ingat-ingat-psg-juara-bertahan-liga-champions
https://sport.detik.com/sepakbola/uefa/d-8655270/yamal-cuma-kurang-trofi-liga-champions-bertekad-juara-di-musim-ini
https://sport.detik.com
https://sport.detik.com/
https://sport.detik.com/sport-lain/d-8655872/pelatih-timnas-voli-putra-ri-targetkan-medali-di-asian-games-2026
https://sport.detik.com/sepakbola/uefa/d-8655901/enzo-fernandez-sanjung-haaland-siap-layani-dengan-banyak-assist
https://sport.detik.com/sepakbola/bola-dunia/d-8655896/jangan-kaget-kalau-mbappe-raih-ballon-dor-2026
https://sport.detik.com/sepakbola/liga-indonesia/d-8655279/fix-persija-menjamu-persib-di-sugbk
https://sport.detik.com/bold-riders
https://sport.detik.com/sepakbola/liga-indonesia/d-8656106/sjh-disiapkan-buat-fifa-asean-cup-persib-terpaksa-main-di-gbla

### Filter URL artikel Sport

In [24]:
def is_sport_article(url):
    parsed = urlparse(url)

    if parsed.netloc != "sport.detik.com":
        return False

    path = parsed.path.lower()

    # URL umum yang bukan artikel
    excluded = [
        "/",
        "/index",
        "/indeks",
        "/search",
        "/video",
        "/foto"
    ]

    if path in excluded:
        return False

    # Hindari URL folder/kategori
    if path.endswith("/"):
        return False

    return True

In [25]:
sport_article_urls = [
    url
    for url in sport_urls_test
    if is_sport_article(url)
]

sport_article_urls = list(dict.fromkeys(sport_article_urls))

print(
    "URL artikel Sport:",
    len(sport_article_urls)
)

URL artikel Sport: 68

### Cek URL Sport

In [26]:
for url in sport_article_urls[:20]:
    print(url)

https://sport.detik.com/sepakbola/uefa/d-8655331/luis-enrique-nggak-mau-ingat-ingat-psg-juara-bertahan-liga-champions
https://sport.detik.com/sepakbola/uefa/d-8655270/yamal-cuma-kurang-trofi-liga-champions-bertekad-juara-di-musim-ini
https://sport.detik.com
https://sport.detik.com/sport-lain/d-8655872/pelatih-timnas-voli-putra-ri-targetkan-medali-di-asian-games-2026
https://sport.detik.com/sepakbola/uefa/d-8655901/enzo-fernandez-sanjung-haaland-siap-layani-dengan-banyak-assist
https://sport.detik.com/sepakbola/bola-dunia/d-8655896/jangan-kaget-kalau-mbappe-raih-ballon-dor-2026
https://sport.detik.com/sepakbola/liga-indonesia/d-8655279/fix-persija-menjamu-persib-di-sugbk
https://sport.detik.com/bold-riders
https://sport.detik.com/sepakbola/liga-indonesia/d-8656106/sjh-disiapkan-buat-fifa-asean-cup-persib-terpaksa-main-di-gbla
https://sport.detik.com/sepakbola/liga-indonesia/d-8655338/head-to-head-persija-vs-persib-10-laga-terbaru-macan-kemayoran-kurang-oke
https://sport.detik.com/sport-lain/d-8655779/asian-games-2026-prabowo-janjikan-bonus-rp-3-m-untuk-peraih-emas
https://sport.detik.com/sport-lain
https://sport.detik.com/sepakbola/uefa/d-8655905/5-hat-trick-tercepat-liga-champions-tak-ada-messi-dan-ronaldo
https://sport.detik.com/sepakbola/uefa/d-8655900/feyenoord-tahu-lawan-barcelona-bakalan-sulit
https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
https://sport.detik.com/sport-lain/d-8656181/asian-games-ketum-pbti-yakin-taekwondo-bisa-berkontribusi-untuk-indonesia
https://sport.detik.com/sepakbola/uefa/d-8655182/ngerinya-haaland-di-liga-champions-satu-gol-per-laga
https://sport.detik.com/sepakbola/uefa/d-8655195/arsenal-mau-buka-liga-champions-dengan-wow
https://sport.detik.com/sepakbola/uefa/d-8654896/haaland-samai-aguero-jadi-top-skor-man-city-di-liga-champions
https://sport.detik.com/aboutthegame

### Membuat fungsi ekstraksi artikel

In [27]:
def extract_article(url):
    try:
        html = get_html(url)

        if not html:
            return None

        text = trafilatura.extract(
            html,
            include_comments=False,
            include_tables=False,
            favor_precision=True
        )

        if not text:
            return None

        text = text.strip()

        if len(text) < 200:
            return None

        return text

    except Exception as e:
        print(f"Gagal ekstraksi: {url}")
        print(e)
        return None

### Tes satu artikel

In [28]:
test_url = sport_article_urls[0]

print(test_url)

https://sport.detik.com/sepakbola/uefa/d-8655331/luis-enrique-nggak-mau-ingat-ingat-psg-juara-bertahan-liga-champions

In [29]:
text = extract_article(test_url)

if text:
    print(text[:3000])
else:
    print("Isi artikel tidak ditemukan")

Paris Saint-Germain (PSG) adalah juara bertahan Liga Champions. Status itu nggak mau diingat-ingat pelatih Luis Enrique!
PSG dua kali menangi Liga Champions di dua musim terakhir. Inter Milan dan Arsenal jadi korban di laga final.
PSG tentu kembali jadi favorit untuk jadi kampiun Liga Champions musim 2026/27 ini. Akan tetapi, pelatih Luis Enrique ogah bicarakan kans terlalu jauh dan ogah ingat-ingat status juara bertahan!
"Yang berlalu sudah berlalu," tegas Enrique dilansir dari situs resmi UEFA.
"Sama seperti lisensi berkendara, itu harus diperbarui," sambungnya.
Luis Enrique tidak mau PSG terlena dan di atas angin. Kompetisi Liga Champions selalu berat.
Lawan pertama mereka adalah Slovan Bratislava, yang akan main pada Kamis (10/9) pukul 02.00 WIB. PSG memulai Ligue 1 dengan pincang, Enrique makin peringatkan timnya.
"Semua orang bersemangat untuk bertanding melawan kami. Kami harus menerimanya dan keluar dari zona nyaman," tegasnya.
"Saya siap menunjukkan bahwa timi ini harus terus memperbarui diri setiap hari," tutupnya.
(aff/ran)

### Membuat crawler artikel

In [30]:
def crawl_articles(urls, label, target=100):
    
    data = []
    visited = set()

    for url in urls:

        if len(data) >= target:
            break

        if url in visited:
            continue

        visited.add(url)

        print(
            f"[{label}] "
            f"{len(data) + 1}/{target} "
            f"-> {url}"
        )

        text = extract_article(url)

        if text is None:
            print("  -> Gagal mendapatkan isi")
            continue

        data.append({
            "id": len(data) + 1,
            "isi_berita": text,
            "label": label
        })

        print("  -> Berhasil")

        # jeda antar-request
        time.sleep(1)

    return data

### Membuat fungsi pagination

In [31]:
def get_sport_index_url(page):
    
    if page == 1:
        return "https://sport.detik.com/indeks"
    
    return f"https://sport.detik.com/indeks?page={page}"

### Tes pagination

In [32]:
for page in range(1, 6):
    print(get_sport_index_url(page))

https://sport.detik.com/indeks
https://sport.detik.com/indeks?page=2
https://sport.detik.com/indeks?page=3
https://sport.detik.com/indeks?page=4
https://sport.detik.com/indeks?page=5

### Mengumpulkan URL Sport

In [33]:
def collect_sport_urls(max_pages=10, target_urls=150):
    
    all_urls = set()

    for page in range(1, max_pages + 1):

        index_url = get_sport_index_url(page)

        print(
            f"Mengambil indeks Sport halaman {page}"
        )

        urls = get_article_links(
            index_url,
            "sport.detik.com"
        )

        for url in urls:

            if is_sport_article(url):
                all_urls.add(url)

        print(
            f"Total URL unik: {len(all_urls)}"
        )

        if len(all_urls) >= target_urls:
            break

        time.sleep(1)

    return list(all_urls)

### Menjalankan pengumpulan Sport

In [34]:
sport_urls = collect_sport_urls(
    max_pages=10,
    target_urls=150
)

Mengambil indeks Sport halaman 1
Total URL unik: 34
Mengambil indeks Sport halaman 2
Total URL unik: 54
Mengambil indeks Sport halaman 3
Total URL unik: 74
Mengambil indeks Sport halaman 4
Total URL unik: 94
Mengambil indeks Sport halaman 5
Total URL unik: 113
Mengambil indeks Sport halaman 6
Total URL unik: 132
Mengambil indeks Sport halaman 7
Total URL unik: 151

In [35]:
print("Total URL Sport:", len(sport_urls))

Total URL Sport: 151

### Crawling 100 Sport

In [36]:
sport_data = crawl_articles(
    sport_urls,
    label="sport",
    target=100
)

[sport] 1/100 -> https://sport.detik.com
  -> Gagal mendapatkan isi
[sport] 1/100 -> https://sport.detik.com/fotosport/d-8639993/obor-menyala-indonesia-siap-berlaga-di-asian-games-2026
  -> Berhasil
[sport] 2/100 -> https://sport.detik.com/sport-lain/d-8649199/wec-2026-paruh-kedua-musim-dimulai-team-wrt-32-lebih-pede
  -> Berhasil
[sport] 3/100 -> https://sport.detik.com/raket/d-8641072/campus-league-badminton-lahirkan-talenta-baru
  -> Berhasil
[sport] 4/100 -> https://sport.detik.com/sport-lain/d-8655779/asian-games-2026-prabowo-janjikan-bonus-rp-3-m-untuk-peraih-emas
  -> Berhasil
[sport] 5/100 -> https://sport.detik.com/sport-lain/d-8648160/pemanasan-timnas-basket-3x3-di-taiwan-jelang-asian-games-2026
  -> Berhasil
[sport] 6/100 -> https://sport.detik.com/raket/d-8641178/seri-keempat-m-15-mens-world-tennis-championship-dimulai
  -> Berhasil
[sport] 7/100 -> https://sport.detik.com/sport-lain/d-8639771/menangi-debut-ufc-bilal-hasan-samai-rekor-jeka-saragih
  -> Berhasil
[sport] 8/100 -> https://sport.detik.com/moto-gp/d-8651046/ktm-suka-antusiasme-luca-marini
  -> Berhasil
[sport] 9/100 -> https://sport.detik.com/raket/d-8654666/ganda-campuran-indonesia-kembali-rombak-pemain
  -> Berhasil
[sport] 10/100 -> https://sport.detik.com/moto-gp/d-8644946/francesco-bagnaia-di-titik-terendah
  -> Berhasil
[sport] 11/100 -> https://sport.detik.com/sport-lain/d-8654641/ambisi-morgan-holindo-jadi-juara-nasional-eshark-rok-cup-2027
  -> Berhasil
[sport] 12/100 -> https://sport.detik.com/sportstyle/d-8651462/jete-run-festival-2026-selesai-masuk-rekor-muri
  -> Berhasil
[sport] 13/100 -> https://sport.detik.com/sport-lain/d-8643074/bilal-hasan-bikin-legenda-ufc-ini-kagum
  -> Berhasil
[sport] 14/100 -> https://sport.detik.com/moto-gp/d-8647200/marc-marquez-makin-dekat-jorge-martin-akan-lawan
  -> Berhasil
[sport] 15/100 -> https://sport.detik.com/raket/d-8645423/hasil-china-masters-2026-sabar-reza-menang-dua-gim-langsung
  -> Berhasil
[sport] 16/100 -> https://sport.detik.com/sport-lain/d-8642711/jawa-timur-juara-kejurnas-panahan-tradisional-2026
  -> Berhasil
[sport] 17/100 -> https://sport.detik.com/moto-gp/d-8639619/hasil-kualifikasi-motogp-aragon-2026-bezzecchi-pole-disusul-marquez
  -> Berhasil
[sport] 18/100 -> https://sport.detik.com/sportstyle/d-8640052/pabki-catatkan-rekor-muri-tancapkan-600-pisau
  -> Berhasil
[sport] 19/100 -> https://sport.detik.com/raket/d-8642931/china-masters-2026-jonatan-christie-kalahkan-leong-jun-hao-maju-ke-16-besar
  -> Berhasil
[sport] 20/100 -> https://sport.detik.com/basket
  -> Gagal mendapatkan isi
[sport] 20/100 -> https://sport.detik.com/infografis
  -> Gagal mendapatkan isi
[sport] 20/100 -> https://sport.detik.com/advertorial-news-block/d-8651455/menkomdigi-imbau-warga-waspadai-dampak-erupsi-anak-krakatau
  -> Berhasil
[sport] 21/100 -> https://sport.detik.com/moto-gp/d-8645850/agar-motogp-indonesia-2026-sukses-di-dalam-dan-luar-lintasan
  -> Berhasil
[sport] 22/100 -> https://sport.detik.com/sport-lain/d-8642499/kejurnas-hoki-indoor-2026-jabar-juara-putra-jatim-kampiun-sektor-putri
  -> Berhasil
[sport] 23/100 -> https://sport.detik.com/raket/d-8651603/mens-world-tennis-championship-karan-singh-juara-seri-iv
  -> Berhasil
[sport] 24/100 -> https://sport.detik.com/sportstyle/d-8653076/ngedadak-padel-ketika-padel-jadi-ajang-reuni
  -> Berhasil
[sport] 25/100 -> https://sport.detik.com/sport-lain/d-8651374/wec-2026-sean-gelael-balapan-di-austin-dini-hari-start-p7
  -> Berhasil
[sport] 26/100 -> https://sport.detik.com/sport-lain/d-8649165/bali-bakal-gelar-turnamen-catur-internasional-akhir-oktober
  -> Berhasil
[sport] 27/100 -> https://sport.detik.com/raket/d-8649124/hasil-china-masters-2026-sabar-reza-out-wakil-indonesia-habis
  -> Berhasil
[sport] 28/100 -> https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  -> Berhasil
[sport] 29/100 -> https://sport.detik.com/raket/d-8644579/ini-dia-20-pebulutangkis-indonesia-di-asian-games-2026
  -> Berhasil
[sport] 30/100 -> https://sport.detik.com/moto-gp/d-8646970/gelar-juara-motogp-2026-jadi-ujian-ketahanan-marc-marquez
  -> Berhasil
[sport] 31/100 -> https://sport.detik.com/moto-gp/d-8640747/moto3-aragon-2026-maximo-quiles-menang-veda-ega-posisi-berapa
  -> Berhasil
[sport] 32/100 -> https://sport.detik.com/f1/d-8651642/mamma-mia-antonelli
  -> Berhasil
[sport] 33/100 -> https://sport.detik.com/sport-lain/d-8655636/rizki-juniansyah-siap-debut-di-asian-games-2026-naik-kelas-ke-85-kg
  -> Berhasil
[sport] 34/100 -> https://sport.detik.com/moto-gp/d-8654776/motogp-san-marino-2026-jaga-puncak-klasemen-bukan-prioritas-jorge-martin
  -> Berhasil
[sport] 35/100 -> https://sport.detik.com/raket/d-8650339/mens-world-tennis-championship-rafalentino-ethan-gagal-juara
  -> Berhasil
[sport] 36/100 -> https://sport.detik.com/sport-lain/d-8650342/wec-2026-wrt-32-meraba-cota-dari-hasil-free-practice
  -> Berhasil
[sport] 37/100 -> https://sport.detik.com/moto-gp/d-8642058/duel-300-km-jam-marc-marquez-vs-bezzecchi-di-aragon-motor-seperti-nempel
  -> Berhasil
[sport] 38/100 -> https://sport.detik.com/moto-gp/d-8642734/marc-marquez-sirkuit-mandalika-yang-terburuk-buatku
  -> Berhasil
[sport] 39/100 -> https://sport.detik.com/basket/d-8649778/asian-games-2026-timnas-basket-masuk-grup-neraka-cdm-optimistis
  -> Berhasil
[sport] 40/100 -> https://sport.detik.com/sport-lain/d-8653014/debut-di-rok-cup-indonesia-2026-barra-ghaisan-torehkan-catatan-positif
  -> Berhasil
[sport] 41/100 -> https://sport.detik.com/moto-gp/d-8643612/marc-marquez-beri-pukulan-untuk-rider-rider-aprilia
  -> Berhasil
[sport] 42/100 -> https://sport.detik.com/sport-lain/d-8642668/gtwce-2026-sean-gelael-dkk-gagal-dapat-poin-di-jerman
  -> Berhasil
[sport] 43/100 -> https://sport.detik.com/sport-lain/d-8644322/ketum-koni-pusat-sambut-positif-kejuaraan-pacu-kuda-di-aceh
  -> Berhasil
[sport] 44/100 -> https://sport.detik.com/sport-lain/d-8654342/menuju-asian-games-2026-ketum-koi-tekankan-kolaborasi
  -> Berhasil
[sport] 45/100 -> https://sport.detik.com/sport-lain/d-8654586/ihr-2026-perluas-olahraga-pacuan-kuda-indonesia
  -> Berhasil
[sport] 46/100 -> https://sport.detik.com/moto-gp/d-8640946/motogp-aragon-2026-juara-lagi-marc-marquez-hat-trick-kemenangan
  -> Berhasil
[sport] 47/100 -> https://sport.detik.com/moto-gp/d-8640220/jadwal-motogp-aragon-2026-race-utama-minggu-malam-sore-ada-moto3
  -> Berhasil
[sport] 48/100 -> https://sport.detik.com/sportstyle/d-8647394/bakal-ada-jakarta-vertical-run-2026-bulan-november
  -> Berhasil
[sport] 49/100 -> https://sport.detik.com/moto-gp/d-8640055/strategi-berisiko-yang-menangkan-marc-marquez
  -> Berhasil
[sport] 50/100 -> https://sport.detik.com/raket/d-8654637/mens-world-tennis-championship-hari-baik-untuk-wakil-ri
  -> Berhasil
[sport] 51/100 -> https://sport.detik.com/sport-lain/d-8646269/jalan-panjang-bilal-hasan-menuju-titel-ufc
  -> Berhasil
[sport] 52/100 -> https://sport.detik.com/fotosport/d-8648227/kyrchyn-gorge-jadi-panggung-world-nomad-games
  -> Berhasil
[sport] 53/100 -> https://sport.detik.com/sepakbola
  -> Gagal mendapatkan isi
[sport] 53/100 -> https://sport.detik.com/basket/d-8653694/timnas-basket-putra-di-asian-games-2026-menangi-laga-pertama-dulu
  -> Berhasil
[sport] 54/100 -> https://sport.detik.com/moto-gp/d-8645527/motogp-2026-aprilia-kian-termotivasi-kalahkan-marc-marquez
  -> Berhasil
[sport] 55/100 -> https://sport.detik.com/raket/d-8653071/mens-world-tennis-championship-3-wakil-ri-gagal-ke-babak-utama-seri-v
  -> Berhasil
[sport] 56/100 -> https://sport.detik.com/raket/d-8643860/china-masters-2026-singkirkan-unggulan-1-leo-daniel-ke-16-besar
  -> Berhasil
[sport] 57/100 -> https://sport.detik.com/raket/d-8642692/mens-world-tennis-championship-gunawan-tembus-babak-utama-seri-iv
  -> Berhasil
[sport] 58/100 -> https://sport.detik.com/sport-lain/d-8641175/patrin-buka-suara-soal-kabar-atlet-tuna-rungu-galang-dana
  -> Berhasil
[sport] 59/100 -> https://sport.detik.com/moto-gp/d-8640943/hasil-motogp-aragon-marc-marquez-juara-lagi
  -> Berhasil
[sport] 60/100 -> https://sport.detik.com/sportstyle/d-8641057/atlet-dunia-ramaikan-premiere-padel-indonesia
  -> Berhasil
[sport] 61/100 -> https://sport.detik.com/sport-lain/d-8647346/dki-jakarta-gelar-pon-pantai-2026-bulan-november
  -> Berhasil
[sport] 62/100 -> https://sport.detik.com/sport-lain/d-8655872/pelatih-timnas-voli-putra-ri-targetkan-medali-di-asian-games-2026
  -> Berhasil
[sport] 63/100 -> https://sport.detik.com/sport-lain/d-8642836/arwana-jaya-dan-onic-sport-juara-ipl-season-2
  -> Berhasil
[sport] 64/100 -> https://sport.detik.com/sport-lain/d-8644288/pordasi-akan-optimalkan-lapangan-h-m-hasan-gayo-untuk-olahraga-berkuda
  -> Berhasil
[sport] 65/100 -> https://sport.detik.com/bold-riders
  -> Berhasil
[sport] 66/100 -> https://sport.detik.com/raket/d-8647441/hasil-china-masters-2026-sabar-reza-menang-melaju-ke-perempatfinal
  -> Berhasil
[sport] 67/100 -> https://sport.detik.com/raket/d-8645946/mens-world-tennis-championship-rafalentino-dan-anthony-ke-babak-kedua
  -> Berhasil
[sport] 68/100 -> https://sport.detik.com/moto-gp/d-8639920/klasemen-motogp-2026-usai-marc-marquez-juara-sprint-race-aragon
  -> Berhasil
[sport] 69/100 -> https://sport.detik.com/sport-lain
  -> Gagal mendapatkan isi
[sport] 69/100 -> https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
  -> Berhasil
[sport] 70/100 -> https://sport.detik.com/raket/d-8644222/mens-world-tennis-championship-nathan-barki-lolos-ke-babak-kedua
  -> Berhasil
[sport] 71/100 -> https://sport.detik.com/sportstyle/d-8653975/nikmati-keseruan-lari-di-solo-run-fest-2026-beli-tiketnya-via-brimo
  -> Berhasil
[sport] 72/100 -> https://sport.detik.com/aboutthegame
  -> Berhasil
[sport] 73/100 -> https://sport.detik.com/sport-lain/d-8656170/atlet-muda-modern-pentathlon-punya-kesempatan-karier-di-militer
  -> Berhasil
[sport] 74/100 -> https://sport.detik.com/moto-gp/d-8643938/kampiun-motogp-2026-bukan-yang-paling-banyak-menang-tapi-paling-tenang
  -> Berhasil
[sport] 75/100 -> https://sport.detik.com/g-sport/d-8654605/hut-tni-akan-dimeriahkan-kejuaraan-tingkat-nasional-di-8-cabor
  -> Berhasil
[sport] 76/100 -> https://sport.detik.com/sportstyle/d-8650215/minala-cup-padel-diikuti-lebih-dari-300-peserta
  -> Berhasil
[sport] 77/100 -> https://sport.detik.com/g-sport/d-8645920/atlet-bukan-satu-satunya-kunci-kemajuan-olahraga-nasional
  -> Berhasil
[sport] 78/100 -> https://sport.detik.com/sport-lain/d-8650061/lewat-buku-eks-judoka-tuang-buah-pikiran-untuk-kemajuan-olahraga-nasional
  -> Berhasil
[sport] 79/100 -> https://sport.detik.com/sportstyle/d-8653121/setelah-9-tahun-gelar-basket-kini-ljk-2026-rambah-padel
  -> Berhasil
[sport] 80/100 -> https://sport.detik.com/fotosport/d-8641844/1-049-pelajar-adu-prestasi-di-popprov-dki-jakarta-2026
  -> Berhasil
[sport] 81/100 -> https://sport.detik.com/sport-lain/d-8655303/asian-games-2026-banjir-landa-nagoya-menpora-yakin-jepang-punya-plan-b
  -> Berhasil
[sport] 82/100 -> https://sport.detik.com/moto-gp/d-8656147/tebak-sirkuit-motogp-bisa-dapat-saldo-e-wallet-rp-750-ribu-mau
  -> Berhasil
[sport] 83/100 -> https://sport.detik.com/sport-lain/d-8639683/hasil-ufc-fight-night-286-bilal-hasan-menang-ko-lawan-nilson-rojas
  -> Berhasil
[sport] 84/100 -> https://sport.detik.com/sportstyle/d-8653072/menjaga-gaya-hidup-sehat-lewat-hyrox
  -> Berhasil
[sport] 85/100 -> https://sport.detik.com/sport-lain/d-8639850/hasil-ufc-shanghai-umar-nurmagomedov-kalah-ko
  -> Berhasil
[sport] 86/100 -> https://sport.detik.com/moto-gp/d-8640131/bezzecchi-kalah-bukan-karena-pilihan-ban
  -> Berhasil
[sport] 87/100 -> https://sport.detik.com/sport-lain/d-8648336/avc-continental-2026-bintang-sofyan-hadapi-selandia-baru-di-16-besar
  -> Berhasil
[sport] 88/100 -> https://sport.detik.com/sport-lain/d-8646915/kolaborasi-dengan-npc-kemenpora-genjot-pembinaan-atlet-disabilitas
  -> Berhasil
[sport] 89/100 -> https://sport.detik.com/sportstyle/d-8644207/mangkuluhur-cup-ketika-golf-bukan-lagi-sekadar-olahraga
  -> Berhasil
[sport] 90/100 -> https://sport.detik.com/sportstyle/d-8641153/pentingnya-nge-gym-buat-pelaku-olahraga
  -> Berhasil
[sport] 91/100 -> https://sport.detik.com/sepakbola/indeks
  -> Gagal mendapatkan isi
[sport] 91/100 -> https://sport.detik.com/raket/d-8642232/pbsi-tarik-pemain-dari-china-masters-2026-ri-cuma-kirim-4-wakil
  -> Berhasil
[sport] 92/100 -> https://sport.detik.com/sportstyle
  -> Gagal mendapatkan isi
[sport] 92/100 -> https://sport.detik.com/sport-lain/d-8656176/romy-tahrizi-juara-nasional-shifter-2026-bersama-dewa-united
  -> Berhasil
[sport] 93/100 -> https://sport.detik.com/f1/d-8651436/hasil-f1-gp-italia-2026-kimi-antonelli-menang-mercedes-1-2
  -> Berhasil
[sport] 94/100 -> https://sport.detik.com/raket/d-8656150/bni-dukung-skuad-bulutangkis-indonesia-menuju-asian-games-2026
  -> Berhasil
[sport] 95/100 -> https://sport.detik.com/moto-gp/d-8643496/bagnaia-kena-mental-bos-ducati-ada-masalah-fokus
  -> Berhasil
[sport] 96/100 -> https://sport.detik.com/moto-gp/d-8650870/crutchlow-pilih-ai-ogura-jadi-favorit-setelah-marc-marquez-ini-alasannya
  -> Berhasil
[sport] 97/100 -> https://sport.detik.com/moto-gp/d-8639880/hasil-sprint-race-motogp-aragon-2026-ngacir-marc-marquez-juaranya
  -> Berhasil
[sport] 98/100 -> https://sport.detik.com/moto-gp/d-8640965/klasemen-motogp-2026-marc-marquez-pangkas-jarak-dari-jorge-martin
  -> Berhasil
[sport] 99/100 -> https://sport.detik.com/moto-gp/d-8641495/motogp-aragon-2026-alex-marquez-syukuri-raihan-poin-penting
  -> Berhasil
[sport] 100/100 -> https://sport.detik.com/sport-lain/d-8653123/wrt-32-di-lone-star-le-mans-startnya-sudah-bagus-tapi
  -> Berhasil

In [37]:
print("Jumlah data Sport:", len(sport_data))

Jumlah data Sport: 100

In [38]:
sport_df = pd.DataFrame(sport_data)

sport_df.head()

   id                                         isi_berita  label
0   1  Jakarta - Sebanyak 432 atlet membela Indonesia...  sport
1   2  FIA World Endurance Championship 2026 memasuki...  sport
2   3  Campus League Badminton Regional Semarang tela...  sport
3   4  Kontingen Indonesia bersiap menatap Asian Game...  sport
4   5  Jelang Asian Games 2026, Timnas basket 3x3 put...  sport

## Finance

### Filter URL artikel finane

In [41]:
def is_finance_article(url):
    parsed = urlparse(url)

    if parsed.netloc != "finance.detik.com":
        return False

    path = parsed.path.lower()

    excluded = [
        "/",
        "/index",
        "/indeks",
        "/search",
        "/video",
        "/foto"
    ]

    if path in excluded:
        return False

    if path.endswith("/"):
        return False

    return True

### Mengambil URL Finance

In [42]:
finance_urls_test = get_article_links(
    "https://finance.detik.com/",
    "finance.detik.com"
)

finance_urls_test = [
    url
    for url in finance_urls_test
    if is_finance_article(url)
]

finance_urls_test = list(
    dict.fromkeys(finance_urls_test)
)

print(
    "URL Finance:",
    len(finance_urls_test)
)

URL Finance: 86

### Fungsi pagination Finance

In [43]:
def get_finance_index_url(page):

    if page == 1:
        return "https://finance.detik.com/indeks"

    return f"https://finance.detik.com/indeks?page={page}"

### Tes pagination

In [44]:
for page in range(1, 6):
    print(get_finance_index_url(page))

https://finance.detik.com/indeks
https://finance.detik.com/indeks?page=2
https://finance.detik.com/indeks?page=3
https://finance.detik.com/indeks?page=4
https://finance.detik.com/indeks?page=5

### Mengumpulkan URL Finance

In [45]:
def collect_finance_urls(
    max_pages=10,
    target_urls=150
):

    all_urls = set()

    for page in range(1, max_pages + 1):

        index_url = get_finance_index_url(page)

        print(
            f"Mengambil indeks Finance halaman {page}"
        )

        urls = get_article_links(
            index_url,
            "finance.detik.com"
        )

        for url in urls:

            if is_finance_article(url):
                all_urls.add(url)

        print(
            f"Total URL unik: {len(all_urls)}"
        )

        if len(all_urls) >= target_urls:
            break

        time.sleep(1)

    return list(all_urls)

### Menjalankan pengumpulan sport

In [46]:
finance_urls = collect_finance_urls(
    max_pages=10,
    target_urls=150
)

Mengambil indeks Finance halaman 1
Total URL unik: 36
Mengambil indeks Finance halaman 2
Total URL unik: 56
Mengambil indeks Finance halaman 3
Total URL unik: 76
Mengambil indeks Finance halaman 4
Total URL unik: 94
Mengambil indeks Finance halaman 5
Total URL unik: 114
Mengambil indeks Finance halaman 6
Total URL unik: 134
Mengambil indeks Finance halaman 7
Total URL unik: 153

In [47]:
print(
    "Total URL Finance:",
    len(finance_urls)
)

Total URL Finance: 153

### Crawling 100 Finance

In [48]:
finance_data = crawl_articles(
    finance_urls,
    label="finance",
    target=100
)

[finance] 1/100 -> https://finance.detik.com/moneter/d-8654026/jurus-bank-perkuat-likuiditas-bikin-pertumbuhan-bisnis-tetap-sehat
  -> Berhasil
[finance] 2/100 -> https://finance.detik.com/loker
  -> Gagal mendapatkan isi
[finance] 2/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654222/purbaya-ngaku-tak-pusingkan-anggaran-bgn-tahun-ini-tak-sampai-rp-200-t
  -> Berhasil
[finance] 3/100 -> https://finance.detik.com/energi/d-8654238/pertamina-waspada-solar-subsidi-bocor-selisih-harga-tembus-rp-18-200
  -> Berhasil
[finance] 4/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653186/17-perjalanan-krl-dibatalkan-imbas-perawatan-armada-buatan-inka
  -> Berhasil
[finance] 5/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655674/prabowo-janji-berikan-bonus-rp-3-m-buat-peraih-emas-asian-games-2026
  -> Berhasil
[finance] 6/100 -> https://finance.detik.com/moneter/d-8653044/pinjaman-online-warga-ri-makin-banyak-tembus-rp-105-triliun
  -> Berhasil
[finance] 7/100 -> https://finance.detik.com/energi/d-8654088/bensin-campur-etanol-20-ditargetkan-jalan-2028
  -> Berhasil
[finance] 8/100 -> https://finance.detik.com/moneter/d-8655433/punya-banyak-rencana-cek-penawaran-bri-multiguna-pre-approved
  -> Berhasil
[finance] 9/100 -> https://finance.detik.com/moneter/d-8654356/penerima-bansos-bakal-dibuatkan-rekening-bank
  -> Berhasil
[finance] 10/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653611/harga-emas-diramal-naik-ke-rp-3-juta-lagi-ini-perkiraan-waktunya
  -> Berhasil
[finance] 11/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654769/ratusan-penerbangan-di-inggris-delay-batal-ada-apa
  -> Berhasil
[finance] 12/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654240/harga-masker-mahal-imbas-abu-anak-krakatau-pengawasan-mesti-diperketat
  -> Berhasil
[finance] 13/100 -> https://finance.detik.com/energi
  -> Berhasil
[finance] 14/100 -> https://finance.detik.com/foto-bisnis/d-8654591/cabai-rawit-merah-makin-pedas-harga-tembus-rp91-ribu
  -> Berhasil
[finance] 15/100 -> https://finance.detik.com/berita-ekonomi-bisnis
  -> Berhasil
[finance] 16/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655921/kopdes-diklaim-bikin-negara-hemat-rp-150-t-putus-mata-rantai-rentenir
  -> Berhasil
[finance] 17/100 -> https://finance.detik.com/infrastruktur/d-8654625/4-fakta-utang-whoosh-dialihkan-ke-kemenkeu
  -> Berhasil
[finance] 18/100 -> https://finance.detik.com/foto-bisnis/d-8653603/halim-kembali-beroperasi-mobilitas-penumpang-kembali-bergeliat
  -> Berhasil
[finance] 19/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653651/harga-masker-di-pasar-pramuka-sudah-naik-2-kali-lipat
  -> Berhasil
[finance] 20/100 -> https://finance.detik.com/bursa-dan-valas/d-8653229/dolar-as-hari-ini-menguat-ke-rp-17-646
  -> Berhasil
[finance] 21/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653536/harga-emas-terus-anjlok-2-kabar-ini-jadi-biang-keroknya
  -> Berhasil
[finance] 22/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656172/ini-kesalahan-promosi-di-whatsapp-yang-bikin-calon-customer-kabur
  -> Berhasil
[finance] 23/100 -> https://finance.detik.com/moneter/d-8655777/pemilik-ktp-baru-usia-17-tahun-otomatis-dibuatkan-rekening-bri-atau-bsi
  -> Berhasil
[finance] 24/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653551/ada-demam-masker-di-pasar-pramuka-pembeli-borong-20-box-sekaligus
  -> Berhasil
[finance] 25/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655501/purbaya-kebut-sistem-deteksi-pajak-ekspor-impor-pakai-ai
  -> Berhasil
[finance] 26/100 -> https://finance.detik.com/energi/d-8655368/mglv-resmi-jadi-pemain-ai-data-center
  -> Berhasil
[finance] 27/100 -> https://finance.detik.com/moneter/d-8655766/masyarakat-dibuatkan-rekening-saldo-awal-rp-50-ribu-sumber-apbn-rp-11-t
  -> Berhasil
[finance] 28/100 -> https://finance.detik.com/energi/d-8653496/ada-wacana-badan-geologi-bmkg-digabung-puan-bilang-begini
  -> Berhasil
[finance] 29/100 -> https://finance.detik.com/infrastruktur/d-8654887/otorita-ikn-buka-suara-soal-karhutla-jarak-terdekat-dengan-kipp-30-km
  -> Berhasil
[finance] 30/100 -> https://finance.detik.com/industri/d-8655518/pemerintah-permudah-izin-tenaga-kerja-asing-5-hari-langsung-terbit
  -> Berhasil
[finance] 31/100 -> https://finance.detik.com/energi/d-8654009/b50-ri-bikin-jepang-malaysia-eropa-penasaran-ada-potensi-hemat-rp-170-t
  -> Berhasil
[finance] 32/100 -> https://finance.detik.com/bursa-dan-valas/d-8653498/morgan-stanley-borong-saham-goto-lagi
  -> Berhasil
[finance] 33/100 -> https://finance.detik.com/infrastruktur
  -> Berhasil
[finance] 34/100 -> https://finance.detik.com/info-pangan
  -> Gagal mendapatkan isi
[finance] 34/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655154/bea-cukai-tindak-10-juta-batang-rokok-ilegal-yang-rugikan-negara-rp-8-m
  -> Berhasil
[finance] 35/100 -> https://finance.detik.com/moneter/d-8654414/purbaya-sebut-bank-ri-siap-pungut-pajak-transaksi-digital-luar-negeri
  -> Berhasil
[finance] 36/100 -> https://finance.detik.com/industri
  -> Berhasil
[finance] 37/100 -> https://finance.detik.com/moneter/d-8655804/warga-usia-17-tahun-bakal-otomatis-dapat-rekening-tanpa-pergi-ke-bank
  -> Berhasil
[finance] 38/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653781/purbaya-setahun-jadi-menkeu-berat-badan-turun-sebut-ri-keluar-dari-kutukan-5
  -> Berhasil
[finance] 39/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653765/pengusaha-pertashop-minta-bisa-ikut-jual-pertalite
  -> Berhasil
[finance] 40/100 -> https://finance.detik.com/moneter
  -> Berhasil
[finance] 41/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656126/prabowo-ungkap-kata-pakar-2050-ri-negara-keempat-ekonomi-terbesar-dunia
  -> Berhasil
[finance] 42/100 -> https://finance.detik.com/moneter/d-8656006/bni-biayai-kopdes-merah-putih-dinilai-minim-risiko-kredit-macet
  -> Berhasil
[finance] 43/100 -> https://finance.detik.com/foto-bisnis/d-8655963/berburu-mainan-dan-nostalgia-masa-kecil-di-kampoeng-mainan-blok-m
  -> Berhasil
[finance] 44/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653432/kapal-eks-kri-ki-hajar-dewantara-bakal-dilelang-rp-370-m
  -> Berhasil
[finance] 45/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654509/sudah-lulus-brevet-pajak-ab-saatnya-lanjut-brevet-c-untuk-cv-lebih-kuat
  -> Berhasil
[finance] 46/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654315/telkomproperty-ungkap-pemanfaatan-graha-merah-putih-oleh-bgn-masih-negosiasi
  -> Berhasil
[finance] 47/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656057/kopdes-merah-putih-bakal-gandeng-pnm-dan-pt-pos
  -> Berhasil
[finance] 48/100 -> https://finance.detik.com/bursa-dan-valas/d-8655574/danantara-mau-beli-saham-bei-bursa-bakal-dimiliki-pemerintah
  -> Berhasil
[finance] 49/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654488/purbaya-terjunkan-anak-buah-awasi-ketat-dapur-mbg
  -> Berhasil
[finance] 50/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655060/inggris-larang-total-impor-produk-dari-permukiman-ilegal-israel-di-tepi-barat
  -> Berhasil
[finance] 51/100 -> https://finance.detik.com/bursa-dan-valas
  -> Berhasil
[finance] 52/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653829/negara-kantongi-rp-26-triliun-dari-aset-rampasan
  -> Berhasil
[finance] 53/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8652409/dari-rp-2-41-t-jadi-rp-8-51-t-mengintip-pertumbuhan-pupuk-indonesia
  -> Berhasil
[finance] 54/100 -> https://finance.detik.com/market-research
  -> Berhasil
[finance] 55/100 -> https://finance.detik.com/fintech
  -> Berhasil
[finance] 56/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656183/menaker-soal-formula-upah-minimum-2027-tunggu-aja
  -> Berhasil
[finance] 57/100 -> https://finance.detik.com/energi/d-8653695/pertashop-terancam-tutup-penjualan-pertamax-anjlok-dari-400-jadi-100-liter
  -> Berhasil
[finance] 58/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654602/masih-bingung-kelola-arus-kas-bisnis-jasamu-ikut-program-ini-solusinya
  -> Berhasil
[finance] 59/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654628/alasan-purbaya-kerap-omong-gede-hingga-dicap-sombong-saat-awal-jadi-menkeu
  -> Berhasil
[finance] 60/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655538/anak-krakatau-erupsi-harga-bahan-pokok-aman-ini-kata-mendag
  -> Berhasil
[finance] 61/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653351/airlangga-sebut-bencana-bikin-ekonomi-kontraksi-di-daerah-terdampak
  -> Berhasil
[finance] 62/100 -> https://finance.detik.com/bursa-dan-valas/d-8653232/ihsg-dibuka-menguat-ke-6-639
  -> Berhasil
[finance] 63/100 -> https://finance.detik.com/infrastruktur/d-8653955/70-negara-kumpul-di-kek-kura-kura-bali-bahas-ai-hingga-investasi
  -> Berhasil
[finance] 64/100 -> https://finance.detik.com/foto-bisnis/d-8652806/khawatir-abu-vulkanik-warga-pilih-cuci-pakaian-di-laundry-koin
  -> Berhasil
[finance] 65/100 -> https://finance.detik.com/finansial
  -> Berhasil
[finance] 66/100 -> https://finance.detik.com/energi/d-8654629/pertashop-terancam-tutup-ini-penyebabnya
  -> Berhasil
[finance] 67/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653993/bandara-soetta-sempat-ditutup-barang-ekspor-impor-rp-3-t-mandek
  -> Berhasil
[finance] 68/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655321/bencana-jadi-beban-ekonomi-negara
  -> Berhasil
[finance] 69/100 -> https://finance.detik.com/bursa-dan-valas/d-8653649/ihsg-bergerak-menguat-asing-borong-saham-bbca-bbri
  -> Berhasil
[finance] 70/100 -> https://finance.detik.com/moneter/d-8655958/duit-apbn-dipakai-biayai-buka-rekening-bank-purbaya-buka-suara
  -> Berhasil
[finance] 71/100 -> https://finance.detik.com/cariin-kerja
  -> Berhasil
[finance] 72/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655135/garuda-cek-pesawat-sebelum-terbang-lagi-imbas-abu-vulkanik
  -> Berhasil
[finance] 73/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653337/dorong-kapasitas-ekspor-lpei-kemenkeu-resmikan-48-desa-devisa-di-babel
  -> Berhasil
[finance] 74/100 -> https://finance.detik.com/bursa-dan-valas/d-8655085/emiten-rukun-raharja-rampungkan-akuisisi-5-saham-pt-lng
  -> Berhasil
[finance] 75/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655809/nasib-karyawan-telkom-yang-gedungnya-bakal-ditempati-bgn
  -> Berhasil
[finance] 76/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653800/peran-pengusaha-dalam-ekonomi-nasional-didorong-makin-diperkuat
  -> Berhasil
[finance] 77/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655076/jaguar-land-rover-bakal-phk-4-000-karyawan
  -> Berhasil
[finance] 78/100 -> https://finance.detik.com/foto-bisnis/d-8653254/kapal-logistik-tetap-beroperasi-distribusi-ke-sebesi-dan-sebuku-berjalan-normal
  -> Berhasil
[finance] 79/100 -> https://finance.detik.com/ekonomi-hijau
  -> Berhasil
[finance] 80/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656192/ruu-ketenagakerjaan-dinilai-jauh-dari-harapan-buruh-besok-demo-besar
  -> Berhasil
[finance] 81/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654631/biang-kerok-sulitnya-kembalikan-aset-negara
  -> Berhasil
[finance] 82/100 -> https://finance.detik.com/fintech/d-8655330/bitcoin-masih-diminati-investor-ini-tandanya
  -> Berhasil
[finance] 83/100 -> https://finance.detik.com/infrastruktur/d-8654044/purbaya-buka-bukaan-utang-whoosh-cicilan-rp-1-t-tenor-80-tahun
  -> Berhasil
[finance] 84/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654632/puan-minta-lahan-bekas-karhutla-jadi-kebun-sawit-diusut
  -> Berhasil
[finance] 85/100 -> https://finance.detik.com/bursa-dan-valas/d-8654017/emiten-ratu-dapat-restu-terbitkan-271-juta-saham-baru
  -> Berhasil
[finance] 86/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655752/danantara-soal-bgn-pindah-ke-gedung-telkom-disewa-di-atas-harga-pasar
  -> Berhasil
[finance] 87/100 -> https://finance.detik.com/bursa-dan-valas/d-8654836/rupiah-tekan-dolar-as-ke-level-rp-17-500
  -> Berhasil
[finance] 88/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655064/pengadaan-pemerintah-rp-1-200-t-bisa-jadi-peluang-buat-umkm
  -> Berhasil
[finance] 89/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655278/59-8-juta-rokok-ilegal-di-jakarta-ditindak-bea-cukai-negara-rugi-rp-46-79-m
  -> Berhasil
[finance] 90/100 -> https://finance.detik.com/bursa-dan-valas/d-8655761/adhi-karya-buka-suara-usai-diminta-tutup-semua-anak-usaha
  -> Berhasil
[finance] 91/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654391/7-rekomendasi-jasa-forwarder-import-barang-dari-china-ke-indonesia
  -> Berhasil
[finance] 92/100 -> https://finance.detik.com/moneter/d-8656071/kapan-pembukaan-rekening-buat-masyarakat-dimulai-ini-jawabannya
  -> Berhasil
[finance] 93/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653345/putri-mahkota-swedia-datangi-lombok-ada-apa
  -> Berhasil
[finance] 94/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653266/harga-emas-antam-hari-ini-jatuh
  -> Berhasil
[finance] 95/100 -> https://finance.detik.com/infrastruktur/d-8656017/otorita-ikn-minta-tambah-rp-15-8-triliun-purbaya-jawab-begini
  -> Berhasil
[finance] 96/100 -> https://finance.detik.com/infografis
  -> Gagal mendapatkan isi
[finance] 96/100 -> https://finance.detik.com/bursa-dan-valas/d-8653192/simak-rekomendasi-saham-saat-ihsg-loyo
  -> Berhasil
[finance] 97/100 -> https://finance.detik.com/perencanaan-keuangan
  -> Berhasil
[finance] 98/100 -> https://finance.detik.com/moneter/d-8655862/bri-ditugaskan-buka-rekening-warga-ri-khusus-aceh-lewat-bsi
  -> Berhasil
[finance] 99/100 -> https://finance.detik.com/moneter/d-8654381/ungkap-pemda-punya-rp-100-triliun-nganggur-purbaya-ingatkan-tak-perlu-minjam
  -> Berhasil
[finance] 100/100 -> https://finance.detik.com/solusiukm
  -> Gagal mendapatkan isi
[finance] 100/100 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653574/puan-soroti-lahan-bekas-karhutla-jadi-kebun-sawit-harus-segera-diselidiki
  -> Berhasil

In [49]:
print(
    "Jumlah data Finance:",
    len(finance_data)
)

Jumlah data Finance: 100

### Gabungkan Data

In [50]:
data = sport_data + finance_data

In [51]:
df = pd.DataFrame(data)

### Buat ID ulang

In [52]:
df["id"] = range(1, len(df) + 1)

In [54]:
df = df[
    [
        "id",
        "isi_berita",
        "label"
    ]
]

In [55]:
print("Jumlah data:", len(df))

Jumlah data: 200

### Cek jumlah setiap label

In [56]:
print(
    df["label"].value_counts()
)

label
sport      100
finance    100
Name: count, dtype: int64

### Cek data kosong

In [57]:
print(df.isnull().sum())

id            0
isi_berita    0
label         0
dtype: int64

### Cek duplikasi

In [58]:
print(
    "Duplikat isi berita:",
    df["isi_berita"].duplicated().sum()
)

Duplikat isi berita: 8

### Menghapus data duplikat

In [59]:
df = df.drop_duplicates(
    subset=["isi_berita"]
).reset_index(drop=True)

df["id"] = range(1, len(df) + 1)

In [74]:
print(df["label"].value_counts())

label
sport      100
finance     92
Name: count, dtype: int64

### Simpan Ke csv

In [75]:
df.to_csv(
    "data/dataset_200.csv",
    index=False,
    encoding="utf-8-sig"
)

In [76]:
df_check = pd.read_csv(
    "data/dataset_200.csv"
)

In [77]:
print(df_check.shape)

(192, 3)

In [78]:
df_check.head()

   id                                         isi_berita  label
0   1  Jakarta - Sebanyak 432 atlet membela Indonesia...  sport
1   2  FIA World Endurance Championship 2026 memasuki...  sport
2   3  Campus League Badminton Regional Semarang tela...  sport
3   4  Kontingen Indonesia bersiap menatap Asian Game...  sport
4   5  Jelang Asian Games 2026, Timnas basket 3x3 put...  sport

In [80]:
print("Jumlah data saat ini:", len(df_check))
print("\nDistribusi label:")
print(df_check["label"].value_counts())

Jumlah data saat ini: 192

Distribusi label:
label
sport      100
finance     92
Name: count, dtype: int64

### Data tambahan untuk finance

In [84]:
existing_finance_texts = set(
    df_check.loc[
        df_check["label"] == "finance",
        "isi_berita"
    ]
    .dropna()
    .str.strip()
)

print(
    "Finance unik yang sudah ada:",
    len(existing_finance_texts)
)

Finance unik yang sudah ada: 92

In [85]:
print("Jumlah URL Finance yang tersedia:", len(finance_urls))

Jumlah URL Finance yang tersedia: 153

### Fungsi crawl tambahan untuk finance

In [86]:
def crawl_additional_finance(
    urls,
    existing_texts,
    target=8
):
    
    additional_data = []
    
    for url in urls:
        
        if len(additional_data) >= target:
            break
        
        print(
            f"Memeriksa: "
            f"{len(additional_data)}/{target} "
            f"-> {url}"
        )
        
        text = extract_article(url)
        
        if text is None:
            print("  -> Gagal mendapatkan isi")
            continue
        
        text = text.strip()
        
        # Cek apakah isi sudah pernah ada
        if text in existing_texts:
            print("  -> Duplikat, dilewati")
            continue
        
        # Pastikan artikel belum ditambahkan
        if any(
            item["isi_berita"] == text
            for item in additional_data
        ):
            print("  -> Duplikat tambahan, dilewati")
            continue
        
        additional_data.append({
            "isi_berita": text,
            "label": "finance"
        })
        
        print("  -> Berhasil, artikel baru")
        
        time.sleep(1)
    
    return additional_data

### Crawl data tambahan

In [87]:
finance_tambahan = crawl_additional_finance(
    finance_urls,
    existing_finance_texts,
    target=8
)

Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8654026/jurus-bank-perkuat-likuiditas-bikin-pertumbuhan-bisnis-tetap-sehat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/loker
  -> Gagal mendapatkan isi
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654222/purbaya-ngaku-tak-pusingkan-anggaran-bgn-tahun-ini-tak-sampai-rp-200-t
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8654238/pertamina-waspada-solar-subsidi-bocor-selisih-harga-tembus-rp-18-200
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653186/17-perjalanan-krl-dibatalkan-imbas-perawatan-armada-buatan-inka
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655674/prabowo-janji-berikan-bonus-rp-3-m-buat-peraih-emas-asian-games-2026
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8653044/pinjaman-online-warga-ri-makin-banyak-tembus-rp-105-triliun
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8654088/bensin-campur-etanol-20-ditargetkan-jalan-2028
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655433/punya-banyak-rencana-cek-penawaran-bri-multiguna-pre-approved
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8654356/penerima-bansos-bakal-dibuatkan-rekening-bank
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653611/harga-emas-diramal-naik-ke-rp-3-juta-lagi-ini-perkiraan-waktunya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654769/ratusan-penerbangan-di-inggris-delay-batal-ada-apa
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654240/harga-masker-mahal-imbas-abu-anak-krakatau-pengawasan-mesti-diperketat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8654591/cabai-rawit-merah-makin-pedas-harga-tembus-rp91-ribu
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655921/kopdes-diklaim-bikin-negara-hemat-rp-150-t-putus-mata-rantai-rentenir
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur/d-8654625/4-fakta-utang-whoosh-dialihkan-ke-kemenkeu
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8653603/halim-kembali-beroperasi-mobilitas-penumpang-kembali-bergeliat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653651/harga-masker-di-pasar-pramuka-sudah-naik-2-kali-lipat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8653229/dolar-as-hari-ini-menguat-ke-rp-17-646
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653536/harga-emas-terus-anjlok-2-kabar-ini-jadi-biang-keroknya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656172/ini-kesalahan-promosi-di-whatsapp-yang-bikin-calon-customer-kabur
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655777/pemilik-ktp-baru-usia-17-tahun-otomatis-dibuatkan-rekening-bri-atau-bsi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653551/ada-demam-masker-di-pasar-pramuka-pembeli-borong-20-box-sekaligus
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655501/purbaya-kebut-sistem-deteksi-pajak-ekspor-impor-pakai-ai
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8655368/mglv-resmi-jadi-pemain-ai-data-center
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655766/masyarakat-dibuatkan-rekening-saldo-awal-rp-50-ribu-sumber-apbn-rp-11-t
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8653496/ada-wacana-badan-geologi-bmkg-digabung-puan-bilang-begini
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur/d-8654887/otorita-ikn-buka-suara-soal-karhutla-jarak-terdekat-dengan-kipp-30-km
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/industri/d-8655518/pemerintah-permudah-izin-tenaga-kerja-asing-5-hari-langsung-terbit
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8654009/b50-ri-bikin-jepang-malaysia-eropa-penasaran-ada-potensi-hemat-rp-170-t
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8653498/morgan-stanley-borong-saham-goto-lagi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/info-pangan
  -> Gagal mendapatkan isi
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655154/bea-cukai-tindak-10-juta-batang-rokok-ilegal-yang-rugikan-negara-rp-8-m
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8654414/purbaya-sebut-bank-ri-siap-pungut-pajak-transaksi-digital-luar-negeri
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/industri
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655804/warga-usia-17-tahun-bakal-otomatis-dapat-rekening-tanpa-pergi-ke-bank
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653781/purbaya-setahun-jadi-menkeu-berat-badan-turun-sebut-ri-keluar-dari-kutukan-5
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653765/pengusaha-pertashop-minta-bisa-ikut-jual-pertalite
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656126/prabowo-ungkap-kata-pakar-2050-ri-negara-keempat-ekonomi-terbesar-dunia
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8656006/bni-biayai-kopdes-merah-putih-dinilai-minim-risiko-kredit-macet
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8655963/berburu-mainan-dan-nostalgia-masa-kecil-di-kampoeng-mainan-blok-m
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653432/kapal-eks-kri-ki-hajar-dewantara-bakal-dilelang-rp-370-m
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654509/sudah-lulus-brevet-pajak-ab-saatnya-lanjut-brevet-c-untuk-cv-lebih-kuat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654315/telkomproperty-ungkap-pemanfaatan-graha-merah-putih-oleh-bgn-masih-negosiasi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656057/kopdes-merah-putih-bakal-gandeng-pnm-dan-pt-pos
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8655574/danantara-mau-beli-saham-bei-bursa-bakal-dimiliki-pemerintah
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654488/purbaya-terjunkan-anak-buah-awasi-ketat-dapur-mbg
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655060/inggris-larang-total-impor-produk-dari-permukiman-ilegal-israel-di-tepi-barat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653829/negara-kantongi-rp-26-triliun-dari-aset-rampasan
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8652409/dari-rp-2-41-t-jadi-rp-8-51-t-mengintip-pertumbuhan-pupuk-indonesia
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/market-research
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/fintech
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656183/menaker-soal-formula-upah-minimum-2027-tunggu-aja
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8653695/pertashop-terancam-tutup-penjualan-pertamax-anjlok-dari-400-jadi-100-liter
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654602/masih-bingung-kelola-arus-kas-bisnis-jasamu-ikut-program-ini-solusinya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654628/alasan-purbaya-kerap-omong-gede-hingga-dicap-sombong-saat-awal-jadi-menkeu
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655538/anak-krakatau-erupsi-harga-bahan-pokok-aman-ini-kata-mendag
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653351/airlangga-sebut-bencana-bikin-ekonomi-kontraksi-di-daerah-terdampak
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8653232/ihsg-dibuka-menguat-ke-6-639
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur/d-8653955/70-negara-kumpul-di-kek-kura-kura-bali-bahas-ai-hingga-investasi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8652806/khawatir-abu-vulkanik-warga-pilih-cuci-pakaian-di-laundry-koin
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/finansial
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/energi/d-8654629/pertashop-terancam-tutup-ini-penyebabnya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653993/bandara-soetta-sempat-ditutup-barang-ekspor-impor-rp-3-t-mandek
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655321/bencana-jadi-beban-ekonomi-negara
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8653649/ihsg-bergerak-menguat-asing-borong-saham-bbca-bbri
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655958/duit-apbn-dipakai-biayai-buka-rekening-bank-purbaya-buka-suara
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/cariin-kerja
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655135/garuda-cek-pesawat-sebelum-terbang-lagi-imbas-abu-vulkanik
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653337/dorong-kapasitas-ekspor-lpei-kemenkeu-resmikan-48-desa-devisa-di-babel
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8655085/emiten-rukun-raharja-rampungkan-akuisisi-5-saham-pt-lng
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655809/nasib-karyawan-telkom-yang-gedungnya-bakal-ditempati-bgn
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653800/peran-pengusaha-dalam-ekonomi-nasional-didorong-makin-diperkuat
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655076/jaguar-land-rover-bakal-phk-4-000-karyawan
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8653254/kapal-logistik-tetap-beroperasi-distribusi-ke-sebesi-dan-sebuku-berjalan-normal
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/ekonomi-hijau
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8656192/ruu-ketenagakerjaan-dinilai-jauh-dari-harapan-buruh-besok-demo-besar
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654631/biang-kerok-sulitnya-kembalikan-aset-negara
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/fintech/d-8655330/bitcoin-masih-diminati-investor-ini-tandanya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur/d-8654044/purbaya-buka-bukaan-utang-whoosh-cicilan-rp-1-t-tenor-80-tahun
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654632/puan-minta-lahan-bekas-karhutla-jadi-kebun-sawit-diusut
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8654017/emiten-ratu-dapat-restu-terbitkan-271-juta-saham-baru
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655752/danantara-soal-bgn-pindah-ke-gedung-telkom-disewa-di-atas-harga-pasar
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8654836/rupiah-tekan-dolar-as-ke-level-rp-17-500
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655064/pengadaan-pemerintah-rp-1-200-t-bisa-jadi-peluang-buat-umkm
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655278/59-8-juta-rokok-ilegal-di-jakarta-ditindak-bea-cukai-negara-rugi-rp-46-79-m
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8655761/adhi-karya-buka-suara-usai-diminta-tutup-semua-anak-usaha
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8654391/7-rekomendasi-jasa-forwarder-import-barang-dari-china-ke-indonesia
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8656071/kapan-pembukaan-rekening-buat-masyarakat-dimulai-ini-jawabannya
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653345/putri-mahkota-swedia-datangi-lombok-ada-apa
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653266/harga-emas-antam-hari-ini-jatuh
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infrastruktur/d-8656017/otorita-ikn-minta-tambah-rp-15-8-triliun-purbaya-jawab-begini
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/infografis
  -> Gagal mendapatkan isi
Memeriksa: 0/8 -> https://finance.detik.com/bursa-dan-valas/d-8653192/simak-rekomendasi-saham-saat-ihsg-loyo
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/perencanaan-keuangan
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8655862/bri-ditugaskan-buka-rekening-warga-ri-khusus-aceh-lewat-bsi
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/moneter/d-8654381/ungkap-pemda-punya-rp-100-triliun-nganggur-purbaya-ingatkan-tak-perlu-minjam
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/solusiukm
  -> Gagal mendapatkan isi
Memeriksa: 0/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653574/puan-soroti-lahan-bekas-karhutla-jadi-kebun-sawit-harus-segera-diselidiki
  -> Duplikat, dilewati
Memeriksa: 0/8 -> https://finance.detik.com/foto-bisnis/d-8654578/pemerintah-perkuat-database-penerima-gas-melon-lpg-3kg
  -> Berhasil, artikel baru
Memeriksa: 1/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653167/kemenhub-ungkap-biang-kerok-kemacetan-panjang-pelabuhan-ketapang
  -> Berhasil, artikel baru
Memeriksa: 2/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655808/cicilan-kopdes-merah-putih-pakai-duit-negara-purbaya-jamin-nggak-gagal-bayar
  -> Berhasil, artikel baru
Memeriksa: 3/8 -> https://finance.detik.com/bursa-dan-valas/d-8653180/transisi-bisnis-tbs-energi-toba-jadi-saham-hijau-pertama-bei
  -> Berhasil, artikel baru
Memeriksa: 4/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653500/8-bandara-terdampak-abu-vulkanik-anak-krakatau-kembali-operasi
  -> Berhasil, artikel baru
Memeriksa: 5/8 -> https://finance.detik.com/bursa-dan-valas/d-8655589/kepala-pengawas-bursa-mineral-mau-ri-tentukan-harga-nikel-ini-alasannya
  -> Berhasil, artikel baru
Memeriksa: 6/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8653857/pengusaha-truk-sebut-aturan-zero-odol-belum-siap-di-2027-ini-alasannya
  -> Berhasil, artikel baru
Memeriksa: 7/8 -> https://finance.detik.com/berita-ekonomi-bisnis/d-8655132/elnusa-petrofin-salurkan-bantuan-bagi-pengungsi-erupsi-gunung-sinabung
  -> Berhasil, artikel baru

In [88]:
print(
    "Jumlah Finance tambahan:",
    len(finance_tambahan)
)

Jumlah Finance tambahan: 8

In [89]:
finance_tambahan_df = pd.DataFrame(
    finance_tambahan
)

In [90]:
df_final = pd.concat(
    [df_check, finance_tambahan_df],
    ignore_index=True
)

In [91]:
df_final["id"] = range(
    1,
    len(df_final) + 1
)

In [92]:
df_final = df_final[
    [
        "id",
        "isi_berita",
        "label"
    ]
]

In [93]:
print("Jumlah data:", len(df_final))

print("\nDistribusi label:")
print(df_final["label"].value_counts())

Jumlah data: 200

Distribusi label:
label
sport      100
finance    100
Name: count, dtype: int64

In [94]:
print(
    "Jumlah duplikat:",
    df_final["isi_berita"].duplicated().sum()
)

Jumlah duplikat: 0

In [95]:
print("\nData kosong:")
print(df_final.isnull().sum())

Data kosong:
id            0
isi_berita    0
label         0
dtype: int64

In [96]:
df_final.to_csv(
    "data/dataset_200.csv",
    index=False,
    encoding="utf-8-sig"
)

In [97]:
df_check = pd.read_csv(
    "data/dataset_200.csv"
)

print("Shape:", df_check.shape)
print("\nDistribusi:")
print(df_check["label"].value_counts())

Shape: (200, 3)

Distribusi:
label
sport      100
finance    100
Name: count, dtype: int64

In [98]:
df_check.head()

   id                                         isi_berita  label
0   1  Jakarta - Sebanyak 432 atlet membela Indonesia...  sport
1   2  FIA World Endurance Championship 2026 memasuki...  sport
2   3  Campus League Badminton Regional Semarang tela...  sport
3   4  Kontingen Indonesia bersiap menatap Asian Game...  sport
4   5  Jelang Asian Games 2026, Timnas basket 3x3 put...  sport