In [5]:
import pandas as pd

df = pd.read_csv(
    "data/checkpoint_cleaning.csv"
)

df_all = df[
    ["id", "teks_bersih", "label"]
]

df_all.to_csv(
    "data/teks_bersih.csv",
    index=False,
    encoding="utf-8-sig"
)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_biner = CountVectorizer(
    binary=True
)

matriks_biner = vectorizer_biner.fit_transform(
    df_all["teks_bersih"]
)

fitur_kata = vectorizer_biner.get_feature_names_out()

df_tabel1 = pd.DataFrame(
    matriks_biner.toarray(),
    columns=fitur_kata
)

# Menambahkan label kategori di kolom paling akhir
df_tabel1["label"] = df_all["label"].values

print("=== TABEL 1 (Eksistensi Kata: 0 atau 1) ===")
display(df_tabel1.tail())

=== TABEL 1 (Eksistensi Kata: 0 atau 1) ===

,aadi,aan,aau,abai,abdi,abdul,abdullah,aberdeen,abraham,absen,...,zaro,zein,zeinatma,zero,zigmars,zona,zoom,zuhair,zulfikar,zulfikri
195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
print("Jumlah baris dan kolom pada Tabel 1:", df_tabel1.shape)

Jumlah baris dan kolom pada Tabel 1: (200, 4896)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

# Membuat vectorizer untuk menghitung frekuensi kata
vectorizer_frekuensi = CountVectorizer()

# Transformasi teks_bersih menjadi matriks frekuensi
matriks_frekuensi = vectorizer_frekuensi.fit_transform(
    df_all["teks_bersih"]
)

# Membuat DataFrame (Tabel 2)
df_tabel2 = pd.DataFrame(
    matriks_frekuensi.toarray(),
    columns=vectorizer_frekuensi.get_feature_names_out()
)

# Menambahkan label kategori di kolom paling akhir
df_tabel2["label"] = df_all["label"].values

# Tampilkan hasil Tabel 2
print("=== TABEL 2 (Frekuensi Jumlah Kata) ===")
display(df_tabel2.tail())

=== TABEL 2 (Frekuensi Jumlah Kata) ===

,aadi,aan,aau,abai,abdi,abdul,abdullah,aberdeen,abraham,absen,...,zaro,zein,zeinatma,zero,zigmars,zona,zoom,zuhair,zulfikar,zulfikri
195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
196,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
197,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
198,0,0,0,0,0,0,0,0,0,0,...,0,0,0,6,0,0,0,0,0,0
199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_tabel2.to_csv(
    "data/tabel_frekuensi.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Tabel frekuensi berhasil disimpan.")
print("Lokasi: data/tabel_frekuensi.csv")

Tabel frekuensi berhasil disimpan.
Lokasi: data/tabel_frekuensi.csv

In [10]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

# Membaca data
df_all = pd.read_csv(
    "data/teks_bersih.csv"
)

# Vectorizer frekuensi
vectorizer_frekuensi = CountVectorizer()

# Mengubah teks menjadi matriks frekuensi
matriks_frekuensi = vectorizer_frekuensi.fit_transform(
    df_all["teks_bersih"]
)

# Membuat Transformer TF-IDF
transformer_tfidf = TfidfTransformer()

# Mengubah matriks frekuensi menjadi matriks TF-IDF
matriks_tfidf = transformer_tfidf.fit_transform(
    matriks_frekuensi
)

# Membuat DataFrame TF-IDF
df_tfidf = pd.DataFrame(
    matriks_tfidf.toarray(),
    columns=vectorizer_frekuensi.get_feature_names_out()
)

# Menambahkan label kategori
df_tfidf["label"] = df_all["label"].values

# Tampilkan hasil
print("=== TABEL TF-IDF ===")
display(df_tfidf.tail())

=== TABEL TF-IDF ===

,aadi,aan,aau,abai,abdi,abdul,abdullah,aberdeen,abraham,absen,...,zaro,zein,zeinatma,zero,zigmars,zona,zoom,zuhair,zulfikar,zulfikri
195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.278205,0.0,0.0,0.0,0.0,0.0,0.0
199,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
dataset_sebelum_pca = df_tfidf.copy()

In [12]:
import pandas as pd
from sklearn.decomposition import PCA



# Memisahkan fitur TF-IDF dan label
fitur = dataset_sebelum_pca.drop(
    "label",
    axis=1
)

label = dataset_sebelum_pca["label"]

# Inisialisasi PCA
# Mengurangi jumlah fitur menjadi 5 komponen utama
pca = PCA(
    n_components=5
)

# Melakukan reduksi dimensi
fitur_pca = pca.fit_transform(
    fitur
)

# Membuat nama kolom PC1, PC2, PC3, PC4, PC5
kolom_pca = [
    f"PC{i+1}"
    for i in range(fitur_pca.shape[1])
]

# Membuat DataFrame setelah PCA
dataset_sesudah_pca = pd.DataFrame(
    fitur_pca,
    columns=kolom_pca
)

# Menambahkan label
dataset_sesudah_pca["label"] = label.values

# Menampilkan hasil
print(
    f"Jumlah kolom sebelum PCA : "
    f"{dataset_sebelum_pca.shape[1]}"
)

print(
    f"Jumlah kolom sesudah PCA : "
    f"{dataset_sesudah_pca.shape[1]}"
)

print("\n=== DATASET SETELAH PCA ===")
display(dataset_sesudah_pca.head())

Jumlah kolom sebelum PCA : 4896
Jumlah kolom sesudah PCA : 6

=== DATASET SETELAH PCA ===

        PC1       PC2       PC3       PC4       PC5  label
0 -0.101390 -0.211006  0.194054 -0.303951 -0.040158  sport
1  0.092005 -0.125448 -0.025522  0.051922 -0.157391  sport
2 -0.030194 -0.121328  0.049761 -0.062238 -0.035219  sport
3 -0.130095 -0.061101  0.236201 -0.297409  0.349171  sport
4 -0.077041 -0.261359  0.233182 -0.188436  0.083250  sport

In [13]:
print("=== VARIANCE PCA ===")

for i, variance in enumerate(
    pca.explained_variance_ratio_,
    start=1
):
    print(
        f"PC{i}: {variance * 100:.2f}%"
    )

print(
    f"\nTotal variance yang dipertahankan: "
    f"{pca.explained_variance_ratio_.sum() * 100:.2f}%"
)

=== VARIANCE PCA ===
PC1: 3.98%
PC2: 2.42%
PC3: 1.92%
PC4: 1.91%
PC5: 1.58%

Total variance yang dipertahankan: 11.81%

In [14]:
dataset_sesudah_pca.to_csv(
    "data/dataset_pca.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset hasil PCA berhasil disimpan.")
print("Lokasi: data/dataset_pca.csv")

Dataset hasil PCA berhasil disimpan.
Lokasi: data/dataset_pca.csv

In [15]:
# One Hot Encoding / Encoding label
dataset_sesudah_pca["label"] = dataset_sesudah_pca["label"].map({
    "sport": 1,
    "finance": 0
})

# Tampilkan hasil
print("=== DATASET PCA SETELAH ENCODING LABEL ===")
display(dataset_sesudah_pca.head())

=== DATASET PCA SETELAH ENCODING LABEL ===

        PC1       PC2       PC3       PC4       PC5  label
0 -0.101390 -0.211006  0.194054 -0.303951 -0.040158      1
1  0.092005 -0.125448 -0.025522  0.051922 -0.157391      1
2 -0.030194 -0.121328  0.049761 -0.062238 -0.035219      1
3 -0.130095 -0.061101  0.236201 -0.297409  0.349171      1
4 -0.077041 -0.261359  0.233182 -0.188436  0.083250      1

In [16]:
dataset_sesudah_pca.to_csv(
    "data/dataset_pca_encoding.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset PCA dengan label encoding berhasil disimpan.")

Dataset PCA dengan label encoding berhasil disimpan.